apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myportfolio
  template:
    metadata:
      labels:
        app: myportfolio
    spec:
      containers:
        - name: myportfolio
          image: muzammil78/myportfolio
          ports:
            - containerPort: 3000
